# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7401485133e6f737f2329dbebc942ea26d9fa824c28752df553a404585c3fb6b6ed91f69024e427c54ff0f4927ee70e23146442f06b14fa8b2f7b75cab4000b4

test:
  secret_key_base: 3b389aaf0133e3512154cb340e3ef66b0f3377fd5910a81932f693cf650887d8bbdd4c3009cfad678d559af741256952c2c59531a60bdb9f115af0f14f17a826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
